# Generated by Django 5.1.1 on 2024-09-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_created',
            new_name='is_completed',
        ),
    ]
